### ISSUE TITLE
There is no option to remove;reset cache files

### ISSUE THREAD

**Issue by uniZero** [Diblo/KODI-Popcorn-Time#34] opened 2015-08-30 06:43 UTC
Some plugin functionality breaks permanently if the listing cache files become corrupted. In my case, this happened because I ran out of disk space while using KODI-Popcorn-Time. After re-launching KODI with more available HDD space I would get an error message every time I tried to open a list/category (e.g. "most popular") - that I had opened _before_. The one page I never opened worked.

Things I tried:

+ Uninstalling the KODI-Popcorn-Time plugin and re-installing it

What fixed the problem:

+ re-installing the program after _manually_ deleting the `...AppData\Roaming\Kodi\userdata\addon_data\plugin.video.kodipopcorntime` folder

It would be useful if there was an option somewhere in the plugin interface to do this. Automatically displaying a prompt such as "would you like to reset the cache?" after error messages are displayed could work as well.

**Comment by uniZero** [comment] 2015-08-30 06:51
Additionally, based on what I encountered above this doesn't seem to be true (from repo readme):

> KODI Popcorn Time will pre-allocate the whole file before download. So if you want to watch a 4GB video, you'll need the 4GB.

For clarfication: I tried playing a 1080p movie with ~100MB of free space and it still downloaded the initial buffer - it didn't play anything (and stopped itself) but that initial buffer is still downloaded regardless of how much HDD space is remaining.

**Comment by Diblo** [comment] 2015-09-03 15:58
This is a duplicate of https://github.com/Diblo/KODI-Popcorn-Time/issues/34

**Comment by Diblo** [comment] 2015-09-03 16:25
Hi @uniZero 
Thanks for your feedback

The problem with leftover occurs when the program crashes for different reasons. I are therefore considering how I can solve the problem in the most elegant way. But a solution will first come in version 0.7.0.
Regarding warning about insufficient space. It is not possible since KODI Popcorn Time supports network folders.

Greetings
Diblo

**Comment by chakhdin** [comment] 2015-09-15 06:30
This should be closed now, I guess

**Closed** 2015-09-21 11:23 UTC
Labels: Bug
