### ISSUE TITLE
Script Failed

### ISSUE THREAD

**Issue by gregpa** [Diblo/KODI-Popcorn-Time#17] opened 2015-07-22 18:01 UTC
Loaded with the most recent release of the repository and add-on.  I get the movie listing,  but it has a script failed issue. the movie tries to buffer, but ultimately fails.
-- correction.  All seems to be well after update to Kodi 15

**Comment by Diblo** [comment] 2015-07-25 09:23
Hello @gregpa 
Thank you for created an error report.
Can you post or link to your kodi.log file? - [Easy Log file guide.](http://kodi.wiki/view/Log_file/Easy)
If you have more questions on how you post your log file, please feel free to ask.

**Comment by Diblo** [comment] 2015-08-07 08:46
This is a duplicate of https://github.com/Diblo/KODI-Popcorn-Time/issues/16

**Comment by cunca1975** [comment] 2015-08-17 13:36
i have the same problem

**Closed** 2015-08-27 23:40 UTC
Labels: Duplicate
