### ISSUE TITLE
Fire TV, there are problems with golang.

### ISSUE THREAD

**Issue by iAYMANi** [Diblo/KODI-Popcorn-Time#67] opened 2015-10-03 13:20 UTC
thanks you Diblo

I have try Alpha version 2 to my Amazon Fire TV, there are problems with golang.

I have try Alpha version 2 to my Mac Mini , Everything works great.

**Comment by Diblo** [comment] 2015-10-03 19:28
A duplicate of https://github.com/Diblo/KODI-Popcorn-Time/issues/68

**Closed by Diblo** 2015-10-03 19:28 UTC
Labels: Duplicate
